// Code generated by go-swagger; DO NOT EDIT.

package name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteNameNameIDParams creates a new DeleteNameNameIDParams object
// no default values defined in spec.
func NewDeleteNameNameIDParams() DeleteNameNameIDParams {

	return DeleteNameNameIDParams{}
}

// DeleteNameNameIDParams contains all the bound params for the delete name name ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteNameNameID
type DeleteNameNameIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name ID
	  Required: true
	  In: path
	*/
	NameID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteNameNameIDParams() beforehand.
func (o *DeleteNameNameIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rNameID, rhkNameID, _ := route.Params.GetOK("nameId")
	if err := o.bindNameID(rNameID, rhkNameID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindNameID binds and validates parameter NameID from path.
func (o *DeleteNameNameIDParams) bindNameID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.NameID = raw

	return nil
}
