// Code generated by go-swagger; DO NOT EDIT.

package name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetNameHandlerFunc turns a function with the right signature into a get name handler
type GetNameHandlerFunc func(GetNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetNameHandlerFunc) Handle(params GetNameParams) middleware.Responder {
	return fn(params)
}

// GetNameHandler interface for that can handle valid get name params
type GetNameHandler interface {
	Handle(GetNameParams) middleware.Responder
}

// NewGetName creates a new http.Handler for the get name operation
func NewGetName(ctx *middleware.Context, handler GetNameHandler) *GetName {
	return &GetName{Context: ctx, Handler: handler}
}

/*GetName swagger:route GET /name name getName

get names by name

*/
type GetName struct {
	Context *middleware.Context
	Handler GetNameHandler
}

func (o *GetName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
