// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Hatchery
//
//  Hatchery
//  Schemes:
//    http
//  Host: localhost:8182
//  BasePath: /
//  Version: v1
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
