// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HatcheryError HatcheryError
//
// swagger:model HatcheryError
type HatcheryError struct {

	// error code
	Code int64 `json:"code,omitempty"`

	// a human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail,omitempty"`
}

// Validate validates this hatchery error
func (m *HatcheryError) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HatcheryError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HatcheryError) UnmarshalBinary(b []byte) error {
	var res HatcheryError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
